### ISSUE TITLE
Support for Virtual repeat

### ISSUE THREAD

**Issue by SvenBudak** [DiZhou92/ngx-line-truncation#1]
I have tested ngx-line-truncation and realize that it works on first init. but when i scroll out of a virtual repeat range, and scroll then back, the text is not cutted any more.

**Comment by DiZhou92** [comment]
Hey thanks for reaching out, the fact that it only works for first init is working as expected, this is due to the problem that i had solved with this library does not need re-truncating.
However, we can definitely add this support on by keeping a snapshot of original text element and execute truncation every single time you want.

**Comment by SvenBudak** [comment]
Isnt it maybe not better to make the detection like a observable? because i also want that it works on screen resizing etc...

**Comment by DiZhou92** [comment]
Yeah, resizing is something can be solved directly from what i proposed. 
For Virtual Repeat, can you share some detail on what library you are using?

**Comment by SvenBudak** [comment]
I did a stackblitz: https://stackblitz.com/edit/angular-ybqu68

But the strange thing is... On stackblitz it is working well...
Sometimes are content areas empty. but no problem with the cut of the text...

really really strange...

**Comment by DiZhou92** [comment]
I checked the stackblitz, so basically you are using truncation in a ngFor, correct? Since there is no issue in stackblitz, it's hard for me to investigate the cause.

**Comment by DiZhou92** [comment]
However truncating text on resizing is something I can add in, I will work on it later of this month.

**Comment by DiZhou92** [comment]
Hello @SvenBudak 
As `truncate text on window resize` feature has been added in in https://github.com/DiZhou92/ngx-line-truncation/pull/4 feel free to try it out.
if you experiencing any issue, let me know
