### ISSUE TITLE
hasTruncated event is not emitted when it false

### ISSUE THREAD

**Issue by unlight** [DiZhou92/ngx-line-truncation#10]
```
                if (contentHeight > targetHeight) {
                    truncate(element, this.lines, this.options.ellipsis, this.handler.bind(this));
                }
                else {
                    this.renderer.removeStyle(this.element, 'visibility');
                }
```

When I change `line-truncation` dynamically, it will not call `truncate` with callback `this.handler`, and thus no emit event.

**Comment by DiZhou92** [comment]
I did not quite get what you are trying to do, could you explain more about your intention?

**Comment by unlight** [comment]
Hi @DiZhou92
I'll try explain by example
1. I have long text on narrow screen wich was truncated `hasTruncated` event fired.
2. Then I resize my screen to wide and long text no more long and fit one line (no truncated necessary), but `hasTruncated` still true - it is not resetting or re-emitting to false.

**Comment by DiZhou92** [comment]
I see what you mean, basically you have something that toggles to `hasTruncated`, and when screen size change, it re-execute the truncation, and in that case there is no truncation, and `hasTruncated` still true.

resolution:
need to reset the `hasTruncated` on re-executing.

let me know if I got it right, thanks.

**Comment by unlight** [comment]
Yes, correct

**Comment by DiZhou92** [comment]
fix here:
https://github.com/DiZhou92/ngx-line-truncation/pull/12
