### ISSUE TITLE
Input option to disable truncate

### ISSUE THREAD

**Issue by unlight** [DiZhou92/ngx-line-truncation#11]
My goal is add "see more" button, after pressing it text must expands.
But I cant set `lineCount` to 999+, because of #10

Can we add input property `disabled` which will disable truncation logic?
```
<p [line-truncation]="lineCount" [disabled]="!isExpanded"></p>
```

**Comment by DiZhou92** [comment]
Hi, thanks for reaching out, I can put an update for this. Change will be in this week

**Comment by DiZhou92** [comment]
PR: to https://github.com/DiZhou92/ngx-line-truncation/pull/13 

need to do some test, and then i will update the npm package

**Comment by DiZhou92** [comment]
close this issue as the requirement has been fulfilled
