### ISSUE TITLE
issue with emojis truncation

### ISSUE THREAD

**Issue by tqwqt** [DiZhou92/ngx-line-truncation#17]
Hi
I have an issue with emojis truncation
Here is screenshot of this issue
<img width="804" alt="emoji_issue" src="https://user-images.githubusercontent.com/25612782/70727162-e01a0680-1d07-11ea-958a-1972371d421c.PNG">

and link to the repository, where you can see my code
[https://github.com/tqwqt/angular-line-truncation-test](https://github.com/tqwqt/angular-line-truncation-test)

**Comment by DiZhou92** [comment]
Thanks for reaching out, I will take a look later this week!

**Comment by DiZhou92** [comment]
![Screen Recording 2019-12-15 at 16 36 37 2019-12-15 16_37_49](https://user-images.githubusercontent.com/8729723/70869470-5792a480-1f59-11ea-8787-5b94198aa2d6.gif)

**Comment by DiZhou92** [comment]
I tried your example, but I could not reproduce the issue, can you please confirm that the issue still appear on your end ?

**Comment by tqwqt** [comment]
Hi, issue is still appear
I see you are using MacOS, I am no sure, can this be the cause of different behaviors?

**Comment by DiZhou92** [comment]
could be, I will test it on Windows

**Comment by DiZhou92** [comment]
I might not be able to look at this till next year, my apology for the later fix

**Comment by DiZhou92** [comment]
Hi,  I understand you might still facing this issue if you're still using this library, but I decided to not fix this issue as this requires some physical effort to get and set up on a Windows machine.
