### ISSUE TITLE
Update to Angular 8

### ISSUE THREAD

**Issue by Enngage** [DiZhou92/ngx-line-truncation#2]
Thanks for the lib! Works fine in my Angular 8, but would be good to up the peer deps. 

Just a question - not sure if its intended or not, but line truncating does not work properly when used in combination with fxFlex and changing resolution dynamically. Works ok for hard reload with F5 which is why this is not gonna be an issue in most situation, but still - elements can resize dynamically in some circumstances.

**Comment by DiZhou92** [comment]
Hi there, thank you very much for the feedback.
Yeah, I will put a dependency update soon! For the question, it currently does not support re-truncation on screen resizing, as the possible solution for this has been proposed in https://github.com/DiZhou92/ngx-line-truncation/issues/1, there is already a plan to add this feature in.

**Comment by DiZhou92** [comment]
Hello @Enngage 
As truncate text on window resize feature has been added in in #4 feel free to try it out.
if you experiencing any issue, let me know
