### ISSUE TITLE
When disabled, falls with an error on resize

### ISSUE THREAD

**Issue by pzubar** [DiZhou92/ngx-line-truncation#20]
Hello and thank you for this cool library!

I've faced an issue when setting the `disabled` directive to true, and after that, resizing a window. Here are the screenshots:

![image](https://user-images.githubusercontent.com/36226946/75874743-0d63e580-5e1b-11ea-970a-88706e6bf550.png)

The problem is, that in the `putbackElement`, when disabled, `this.elementClone` is null, so, we've got an exception.

![image](https://user-images.githubusercontent.com/36226946/75874902-5ae05280-5e1b-11ea-9291-26ae63114c95.png)

Any ideas on how to fix it?

Thanks a lot!

**Comment by DiZhou92** [comment]
thanks for submitting the issue, will take a look👍

**Comment by DiZhou92** [comment]
Hi 
Can you provide an example project ? I couldn't reproduce this issue. Thanks.

**Comment by DiZhou92** [comment]
close since close because there was no further conversation
