### ISSUE TITLE
Update to Angular 9

### ISSUE THREAD

**Issue by Enngage** [DiZhou92/ngx-line-truncation#22]
Hey,

as title suggest, can you update peer deps for Angular 9? :)

**Comment by DiZhou92** [comment]
Hey, 
I finished the update, everything works fine for projects running the latest Angular. However there is a typescript compatible issue,
https://github.com/storybookjs/storybook/issues/9463
So that means in order to use the new build, users would have to upgrade to typescript 3.7, which is not compatible to Angular 8 and below
Therefore, I'm holding off this upgrade for now till I find a good solution, if you have any suggestion, please let me know!

**Comment by Enngage** [comment]
Hi, I think you should update this library. Users using older Angular version can use older versions of your packaga. Angular 8 is already out of active support and its LTS ends quite soon - https://angular.io/guide/releases 

Is there really a need to hold on this update? Do old users using angular 8 need to use new versions of this library for angular 9?

**Comment by DiZhou92** [comment]
Hi Enngage,

Thanks for your input, I have updated the dependencies, if there is not issue on your side, I will close this thread.

Regards,
Di

**Comment by Enngage** [comment]
Yeah, we can close this thread. Thanks!

**Comment by Enngage** [comment]
Hi, 

sorry, this is not resolved. You haven't updated peer dependencies in your lib here https://github.com/DiZhou92/ngx-line-truncation/blob/master/projects/line-truncation-lib/package.json#L24 

This is still giving peer dependency warnings when using with Angular 9

**Comment by DiZhou92** [comment]
Oh sorry about that, will get it updated soon. Thank you sir.

Regards,
Di

**Comment by DiZhou92** [comment]
Hi Enngage, I just got peer dependency update, let me know if that works for you. Thanks!

**Comment by Enngage** [comment]
Hi @DiZhou92 ,

Thank you, but it still isn't quite right :)

You cannot combine both `^` and `~` in peer dependencies. See https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json 

You should actually define peer dependencies as:

```
"@angular/common": "~9.0.0",
 "@angular/core": "~9.0.0"
```

So that anyone using Angular 9 can install and use your library without unnecessary warning. You are not depending on any specific features released in e.g. `9.1.7` version, so you don't need to specify it.

**Comment by DiZhou92** [comment]
Hey sorry i made mistake there i guess, was looking for the ~ ^ definition and forget to remove the extra one

**Comment by DiZhou92** [comment]
did an update with ^ because i think its ok to be compatible with any V9

**Comment by Enngage** [comment]
Its ok now, thank you :)
