### ISSUE TITLE
Unable to resolve dependency tree with Angular 11

### ISSUE THREAD

**Issue by lmeerma** [DiZhou92/ngx-line-truncation#47]
Hi all,

this project does not work with Angular 11 or higher due to the following error:

```
Found: @angular/common@11.2.14
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.2.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.1" from ngx-line-truncation@1.6.9
npm ERR! node_modules/ngx-line-truncation
npm ERR!   ngx-line-truncation@"^1.6.9" from the root project
```

I think the dependencies/peer dependencies must be updated or be more vague, e.g. `@angular/common: "^10.0.0 || ^11.0.0"`. This is probably similar to #22 .

Thank you!

**Comment by DiZhou92** [comment]
okay, will update to support v12

**Comment by DiZhou92** [comment]
I updated peer dependency to v12, but i'm not sure if that will backward support v11 in your project, please let me know

https://github.com/DiZhou92/ngx-line-truncation/blob/18a13b9670abaa8407c4862e19a3898e8b4fac04/projects/line-truncation-lib/package.json#L24

**Comment by lmeerma** [comment]
I think it would make more sense to include all the major versions you support like this:

```json
"peerDependencies": {
    "@angular/common": "^^10.0.0 || ^11.0.0 || ^12.0.0",
    "@angular/core":  "^10.0.0 || ^11.0.0 || ^12.0.0"
}
```

I'm not sure what the lowest supported version is so you might add or remove some.

**Comment by DiZhou92** [comment]
done, now V1.71 uses peer dependency 10 to 12. Thank you!
