### ISSUE TITLE
Incorrect peer dependencies

### ISSUE THREAD

**Issue by Enngage** [DiZhou92/ngx-line-truncation#8]
Hi,

Could you please fix the peer dependencies? You are currently 'forcing' `angular@8.0.1` dependency for anyone who uses your lib. You get a message such as:

```
npm WARN ngx-line-truncation@1.2.3 requires a peer of @angular/common@~8.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-line-truncation@1.2.3 requires a peer of @angular/core@~8.0.1 but none is installed. You must install peer dependencies yourself.
```

You should configure `peerDependencies` to contain entire version 8 or I wouldn't be as worried as specifying future proof versions (e.g. > 8).

**Comment by DiZhou92** [comment]
Hey Enngage, i have updated peerDependencies syntax for a wider compatible version range.
Please let me know if this works for you, thank you!

**Comment by Enngage** [comment]
Yeah, all good now. Thanks!
